import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Heading from "./components/Heading";
import Filter from "./components/Filter";
import { Providers } from "./components/Providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={` ${inter.className} 
          bg-white 
          text-black 
            h-full 
          selection:bg-gray-50 `}
      >
        <Providers>
          <Heading />
          <Filter />
          {children}
        </Providers>
      </body>
    </html>
  );
}
